//
// Generated file, do not edit! Created by opp_msgc 4.2 from overlay/simpleOverlay_Skeleton/SkeletonMessage.msg.
//

#ifndef _SKELETONMESSAGE_M_H_
#define _SKELETONMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <CommonMessages_m.h>
// }}



/**
 * Class generated from <tt>overlay/simpleOverlay_Skeleton/SkeletonMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet SkeletonMessage extends BaseOverlayMessage {
 *     
 * }
 * </pre>
 */
class SkeletonMessage : public ::BaseOverlayMessage
{
  protected:

  private:
    void copy(const SkeletonMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SkeletonMessage&);

  public:
    SkeletonMessage(const char *name=NULL, int kind=0);
    SkeletonMessage(const SkeletonMessage& other);
    virtual ~SkeletonMessage();
    SkeletonMessage& operator=(const SkeletonMessage& other);
    virtual SkeletonMessage *dup() const {return new SkeletonMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, SkeletonMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SkeletonMessage& obj) {obj.parsimUnpack(b);}


#endif // _SKELETONMESSAGE_M_H_
