//
// Generated file, do not edit! Created by opp_msgc 4.2 from overlay/simpleOverlay_Chain/CheersMessage.msg.
//

#ifndef _CHEERSMESSAGE_M_H_
#define _CHEERSMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <CommonMessages_m.h>
// }}



/**
 * Class generated from <tt>overlay/simpleOverlay_Chain/CheersMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet CheersMessage extends BaseOverlayMessage {
 *     
 * }
 * </pre>
 */
class CheersMessage : public ::BaseOverlayMessage
{
  protected:

  private:
    void copy(const CheersMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CheersMessage&);

  public:
    CheersMessage(const char *name=NULL, int kind=0);
    CheersMessage(const CheersMessage& other);
    virtual ~CheersMessage();
    CheersMessage& operator=(const CheersMessage& other);
    virtual CheersMessage *dup() const {return new CheersMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, CheersMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CheersMessage& obj) {obj.parsimUnpack(b);}


#endif // _CHEERSMESSAGE_M_H_
